apiVersion: v1
kind: Service
metadata:
  name: argilla-server-lb
  labels:
    app: argilla-server-lb
spec:
  type: LoadBalancer
  selector:
    app: argilla-server
  ports:
    - name: http
      port: 80
      targetPort: 6900