apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: elasticsearch-pvc
  labels:
    app: elasticsearch
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: k8s-storage-policy
  resources:
    requests:
      storage: 2Gi
