apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: extralit-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 50Gi
  storageClassName: k8s-storage-policy
