apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pdf-storage-pvc
  labels:
    app: pdf-storage
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: k8s-storage-policy
  resources:
    requests:
      storage: 2Gi  # Adjust the storage size as needed