blank_issues_enabled: false
contact_links:
  - name: 🗯 Community Discussions
    url: https://join.slack.com/t/extralit/shared_invite/zt-2kt8t12r7-uFj0bZ5SPAOhRFkxP7ZQaQ
    about: Our Slack Community loves to discuss scientific literature data extraction and LLM topics
