apiVersion: v1
kind: Service
metadata:
  name: elasticsearch
  labels:
    app: elasticsearch
spec:
  selector:
    app: elasticsearch-master
  ports:
  - name: http
    port: 9200
# ---
# apiVersion: v1
# kind: Secret
# metadata:
#   name: elasticsearch-password
# type: Opaque
#   password: bXktcGFzc3dvcmQ=