name: base
channels:
  - pytorch
  - conda-forge
  - huggingface
  - plotly
  - defaults
dependencies:
  - beautifulsoup4
  - click
  - dataclasses=0.8
  - dill=0.3.8
  - fastparquet=2024.2.0
  - html5lib=1.1
  - minio=7.2.7
  - multiprocess=0.70.16
  - natsort=8.4.0
  - nest-asyncio=1.6.0
  - networkx
  - nodejs=18.6.0
  - numpy=1.26.4
  - onnx=1.16.1
  - openai=1.30.4
  - openjpeg=2.5.2
  - openssl=3.3.0
  - pandera=0.19.3
  - pandera-base=0.19.3
  - pillow=10.3.0
  - pyarrow
  - plotly=5.22.0
  - pypandoc=1.13
  - python
  - python-dotenv=1.0.1
  - python-multipart=0.0.9
  - scipy=1.13.1
  - pip
  - spacy=3.7.3
  - spacy-legacy=3.0.12
  - spacy-loggers=1.0.5
  - tornado=6.4
  - tqdm=4.66.4
  - transformers=4.25.1
  - tiktoken
  - pytorch
  - pip:
      - albumentations==1.3.1
      - future==1.0.0
      - gliner==0.1.3
      - gliner-spacy==0.0.2
      - h5py==3.11.0
      - html2text==2020.1.16
      - httpx
      - img2table==1.2.8
      - json-repair==0.19.2
      - kaleido==0.2.1
      - langfuse==2.32.0
      - layoutparser==0.3.4
      - llama-index==0.10.37
      - llama-index-agent-openai==0.1.5
      - llama-index-callbacks-langfuse==0.1.4
      - llama-index-cli==0.1.5
      - llama-index-core==0.10.40
      - llama-index-embeddings-openai==0.1.9
      - llama-index-indices-managed-llama-cloud==0.1.5
      - llama-index-legacy==0.9.48
      - llama-index-llms-anthropic==0.1.10
      - llama-index-llms-openai==0.1.19
      - llama-index-multi-modal-llms-openai==0.1.6
      - llama-index-program-openai==0.1.6
      - llama-index-question-gen-openai==0.1.3
      - llama-index-readers-file==0.1.22
      - llama-index-readers-llama-parse==0.1.4
      - llama-index-vector-stores-weaviate==1.0.0
      - llama-parse==0.4.1
      - llamaindex-py-client==0.1.19
      - llmsherpa==0.1.3
      - pandas==1.5.3
      - pdf2image==1.17.0
      - pdfminer-six==20231228
      - pdfplumber==0.11.0
      - pikepdf==8.15.1
      - pydantic==2.7.2
      - pydantic-core==2.18.3
      - pymdown-extensions==10.8.1
      - pymupdf==1.23.6
      - pymupdfb==1.23.6
      - pypdf==4.2.0
      - pypdfium2==4.30.0
      - python-doctr==0.8.1
      - python-levenshtein==0.23.0
      - requests==2.32.3
      - scikit-image==0.22.0
      - scikit-learn==1.4.2
      - sentence-transformers==2.2.2
      - setfit==0.7.0
      - span-marker==1.5.0
      - textdescriptives==2.7.1
      - timm==0.9.16
      - tokenizers==0.15.2
      - typer
      - unstructured==0.12.3
      - unstructured-client==0.16.0
      - unstructured-inference==0.7.27
      - unstructured-pytesseract==0.3.12
      - wandb==0.16.5
      - weaviate-client==4.6.3
