apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: k8-storage-policy
provisioner: rancher.io/local-path
reclaimPolicy: Retain
volumeBindingMode: Immediate
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: elastic-pv
spec:
  capacity:
    storage: 4Gi  # specify the size of the volume
  volumeMode: Filesystem  # can also be Block
  accessModes:
    - ReadWriteOnce  # The volume can be mounted as read-write by a single node
  storageClassName: k8s-storage-policy
  persistentVolumeReclaimPolicy: Retain
  local:
    path: "/usr/share/elasticsearch/data"  
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - kind-control-plane  # replace with your node name
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: postgres-pv
spec:
  capacity:
    storage: 9Gi  # specify the size of the volume
  volumeMode: Filesystem  # can also be Block
  accessModes:
    - ReadWriteOnce  # The volume can be mounted as read-write by a single node
  storageClassName: k8s-storage-policy
  persistentVolumeReclaimPolicy: Retain
  local:
    path: "/var/lib/postgresql/data"
  nodeAffinity: 
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In  
          values:
          - kind-control-plane

